# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_auto_20170814_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='legacy',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
