# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phone', '0005_auto_20170816_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Celt'), (-1, 'Necelt')])),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='negative_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='positive_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='rating_value',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='anonymous_session',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phonerating',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.Phone'),
        ),
        migrations.AddField(
            model_name='phonerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='phonerating',
            unique_together=set([('phone', 'user')]),
        ),
    ]
