# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_auto_20170817_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
