# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0009_auto_20170831_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_raw_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
