# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0010_comment_author_raw_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrating',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phonerating',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
